# Generated by Django 2.0.7 on 2018-09-03 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('streetAddress', models.CharField(max_length=50)),
                ('cityAddress', models.CharField(max_length=16)),
                ('postCodeAddress', models.IntegerField(max_length=4)),
                ('stateAddress', models.CharField(max_length=3)),
                ('DOB', models.DateField()),
                ('driverLicenceNumber', models.IntegerField(max_length=9)),
                ('Occupation', models.CharField(max_length=50)),
                ('phoneNumber', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('userName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('dateJoined', models.DateField()),
                ('lastLogin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('streetAddress', models.CharField(max_length=50)),
                ('cityAddress', models.CharField(max_length=16)),
                ('postCodeAddress', models.IntegerField(max_length=4)),
                ('stateAddress', models.CharField(max_length=3)),
                ('DOB', models.DateField()),
                ('TFN', models.IntegerField(max_length=9)),
                ('phoneNumber', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('userName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('dateJoined', models.DateField()),
                ('lastLogin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='In',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Inspects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crcapp.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoiceID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paymentType', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('orderDate', models.DateField()),
                ('pickupDate', models.DateField()),
                ('returnDate', models.DateField()),
                ('customerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crcapp.Customer')),
                ('employeeID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crcapp.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='OrderFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Rents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crcapp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('storeName', models.CharField(max_length=50)),
                ('storePhone', models.BigIntegerField()),
                ('street', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=16)),
                ('state', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicleID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('makeName', models.CharField(max_length=16)),
                ('model', models.CharField(max_length=16)),
                ('series', models.CharField(max_length=16)),
                ('year', models.IntegerField(max_length=4)),
                ('newPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('enginesize', models.DecimalField(decimal_places=1, max_digits=2)),
                ('fuelSystem', models.CharField(max_length=16)),
                ('tankcapacity', models.DecimalField(decimal_places=1, max_digits=3)),
                ('power', models.IntegerField(max_length=3)),
                ('seatingCapacity', models.IntegerField(max_length=2)),
                ('standardTransmission', models.CharField(max_length=6)),
                ('bodyType', models.CharField(max_length=16)),
                ('driveType', models.CharField(max_length=3)),
                ('wheelbase', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='rents',
            name='vehicleID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crcapp.Vehicle'),
        ),
        migrations.AddField(
            model_name='orderfor',
            name='carID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crcapp.Vehicle'),
        ),
        migrations.AddField(
            model_name='orderfor',
            name='orderID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crcapp.Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickupStoreID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pickupstore', to='crcapp.Store'),
        ),
        migrations.AddField(
            model_name='order',
            name='returnStoreID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='returnstore', to='crcapp.Store'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='orderID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crcapp.Order'),
        ),
        migrations.AddField(
            model_name='inspects',
            name='vehicleID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crcapp.Vehicle'),
        ),
        migrations.AddField(
            model_name='in',
            name='storeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crcapp.Store'),
        ),
        migrations.AddField(
            model_name='in',
            name='vehicleID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crcapp.Vehicle'),
        ),
        migrations.AddField(
            model_name='employee',
            name='storeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crcapp.Store'),
        ),
    ]
