# Generated by Django 2.1.1 on 2018-09-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crcapp', '0002_auto_20180909_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='driverLicenceNumber',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='TFN',
            field=models.BigIntegerField(),
        ),
    ]
