# Generated by Django 2.1.1 on 2018-09-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crcapp', '0003_auto_20180917_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cityAddress',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='driverLicenceNumber',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='postCodeAddress',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='stateAddress',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='streetAddress',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='userName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='userName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
