# Generated by Django 2.1.1 on 2018-09-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crcapp', '0005_auto_20180917_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dateJoined',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lastLogin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='occupation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phoneNumber',
            field=models.BigIntegerField(null=True),
        ),
    ]
