# Generated by Django 2.1.1 on 2018-09-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crcapp', '0009_auto_20180920_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='disable',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='disable',
            field=models.BooleanField(default=0),
        ),
    ]
