# Generated by Django 2.1.2 on 2018-10-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crcapp', '0012_auto_20181022_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phoneNumber',
            field=models.BigIntegerField(),
        ),
    ]
