# Generated by Django 2.1.2 on 2018-10-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crcapp', '0013_auto_20181022_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='driverLicenceNumber',
            field=models.BigIntegerField(null=True),
        ),
    ]
