# Generated by Django 2.1.2 on 2018-10-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crcapp', '0014_auto_20181022_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cityAddress',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='customer',
            name='stateAddress',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
